plugins {
	id 'org.springframework.boot' version '3.5.8'
	id 'org.springframework.cloud.contract' version '4.3.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = 17
	targetCompatibility = 17
}

repositories {
	mavenCentral()
}

dependencies {
	implementation('org.springframework.boot:spring-boot-starter-web')
	testImplementation('org.springframework.boot:spring-boot-starter-test')
	testImplementation('org.springframework.cloud:spring-cloud-starter-contract-verifier')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:2025.0.0"
	}
}

contracts {
	// To have the same contract folder as Maven. In Gradle would default to
	// src/contractTest/resources/contracts
	contractsDslDir = file("src/test/resources/contracts")
	packageWithBaseClasses = 'hello'
	baseClassMappings {
		baseClassMapping(".*hello.*", "hello.BaseClass")
	}
}

contractTest {
	useJUnitPlatform()
}
